apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      containers:
        - name: gs-proxy
          image: "{{ .Values.image.repository }}:{{ include "image.tag" . }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.containerSecurityContext | nindent 12 }}
          {{- if .Values.auth.enabled }}
          env:
            - name: PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secret.name }}
                  key: {{ .Values.auth.secret.usernameKey }}
            - name: PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.auth.secret.name }}
                  key: {{ .Values.auth.secret.passwordKey }}
          {{- end }}
