{{- if and .Values.auth.enabled .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  users.yaml: |
    users:
      {{- range .Values.auth.users }}
      - username: {{ .username | quote }}
        password: {{ .password | quote }}
      {{- end }}
{{- end }}
