{{- if and .Values.auth.enabled .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
stringData:
  htpasswd: |
    {{- .Values.auth.htpasswd | nindent 4 }}
{{- end }}
