{{- if and .Values.auth.enabled .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.auth.secret.usernameKey }}: {{ .Values.auth.credentials.username | b64enc | quote }}
  {{ .Values.auth.secret.passwordKey }}: {{ .Values.auth.credentials.password | b64enc | quote }}
{{- end }}