{{- if and .Values.auth.enabled .Values.auth.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "labels.common" . | nindent 4 }}
type: Opaque
data:
  PROXY_USERNAME: {{ .Values.auth.credentials.username | b64enc | quote }}
  PROXY_PASSWOWD: {{ .Values.auth.credentials.password | b64enc | quote }}
{{- end }}
